# Generated by Django 4.1 on 2022-09-13 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextapi', '0002_alter_taskboard_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskboard',
            old_name='user',
            new_name='author',
        ),
    ]
