# Generated by Django 4.1 on 2022-09-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextapi', '0007_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskboards',
            field=models.ManyToManyField(related_name='tasks', to='nextapi.taskboard'),
        ),
    ]
