# Generated by Django 4.1 on 2022-10-07 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextapi', '0008_task_taskboards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskboards',
        ),
        migrations.AlterField(
            model_name='task',
            name='dateCreated',
            field=models.DateField(default=datetime.date(2022, 10, 7)),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeStamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
