# Generated by Django 4.1 on 2022-10-07 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextapi', '0009_remove_task_taskboards_alter_task_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateCreated',
            field=models.DateField(default=datetime.datetime(2022, 10, 7, 18, 57, 13, 847755, tzinfo=datetime.timezone.utc)),
        ),
    ]
