# Generated by Django 4.1 on 2022-10-07 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nextapi', '0010_alter_task_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateCreated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
