# Generated by Django 4.1 on 2022-10-14 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextapi', '0011_alter_task_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskboardtask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nextapi.task'),
        ),
        migrations.AlterField(
            model_name='taskboardtask',
            name='taskBoard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nextapi.taskboard'),
        ),
    ]
